/*
 * Copyright 2017 Zhihu Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
apply plugin: 'com.android.library'

group = 'com.github.nixplay'
version = '1.2.17'

def publishVersionName="1.2.16"
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {}
}
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion
    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
    lintOptions {
        abortOnError false
    }
    buildToolsVersion '28.0.3'
}


// publish {
//     userOrg = "fishkingsin"
//     groupId = "com.github.nixplay"
//     artifactId = "matisse"
//     publishVersion = "$publishVersionName"
//     desc = "zhihu Matisse forwk"
//     licences = ["Apache-2.0"]
//     uploadName = "Matisse"
//     website = "https://github.com/nixplay/Matisse.git"
// }

repositories {
    if (new File("${rootDir}/maven-local").exists()) {
        maven { url uri("${rootDir}/maven-local") }
    }
    google()
    mavenCentral()
    maven { url 'https://maven.google.com' }
    maven { url "https://jitpack.io" }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation "androidx.legacy:legacy-support-v4:1.0.0"
    implementation "androidx.appcompat:appcompat:1.0.0"
    implementation "androidx.recyclerview:recyclerview:1.0.0"

    provided 'com.github.bumptech.glide:glide:4.10.0'
    // subsampling-scale-image-view
    implementation 'com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0'
    implementation 'it.sephiroth.android.library.imagezoom:imagezoom:+'
    implementation 'com.squareup.picasso:picasso:2.8'
    // ImmersionBar
    implementation 'com.gyf.barlibrary:barlibrary:2.3.0'
    implementation 'com.tbruyelle.rxpermissions2:rxpermissions:0.9.5@aar'

}
